In [1]:
import numpy as np 
import pandas as pd 
import os
import glob
import cv2
import random
import matplotlib.pyplot as plt

In [2]:
x_train = np.load("x_train_200.npy")
y_train = np.load("y_train_200.npy")
x_train.shape, y_train.shape

((22046, 200, 200, 3), (22046, 2))

In [3]:
x_val = np.load("x_val_200.npy")
y_val = np.load("y_val_200.npy")
x_val.shape, y_val.shape

((2756, 200, 200, 3), (2756, 2))

In [4]:
x_test = np.load("x_test_200.npy")
y_test = np.load("y_test_200.npy")
x_test.shape, y_test.shape

((2756, 200, 200, 3), (2756, 2))

In [5]:
x_train = x_train.astype('float32')
x_train /= 255

In [6]:
x_val = x_val.astype('float32')
x_val /= 255

In [7]:
x_test = x_test.astype('float32')
x_test /= 255

In [8]:
# check input
print(x_train.shape, y_train.shape, x_val.shape, y_val.shape, x_test.shape, y_test.shape)

(22046, 200, 200, 3) (22046, 2) (2756, 200, 200, 3) (2756, 2) (2756, 200, 200, 3) (2756, 2)


In [11]:
x_train[5][50:100, 60:100]

array([[[0.5803922 , 0.57254905, 0.69411767],
        [0.57254905, 0.5686275 , 0.6901961 ],
        [0.57254905, 0.5686275 , 0.6901961 ],
        ...,
        [0.5568628 , 0.5529412 , 0.6784314 ],
        [0.56078434, 0.5568628 , 0.68235296],
        [0.56078434, 0.5568628 , 0.68235296]],

       [[0.5764706 , 0.57254905, 0.69411767],
        [0.57254905, 0.5686275 , 0.69411767],
        [0.57254905, 0.5686275 , 0.69411767],
        ...,
        [0.56078434, 0.5568628 , 0.68235296],
        [0.56078434, 0.5568628 , 0.68235296],
        [0.56078434, 0.5568628 , 0.68235296]],

       [[0.5764706 , 0.57254905, 0.69803923],
        [0.5803922 , 0.5764706 , 0.7019608 ],
        [0.5803922 , 0.5764706 , 0.7019608 ],
        ...,
        [0.5686275 , 0.5647059 , 0.6901961 ],
        [0.5686275 , 0.5647059 , 0.6901961 ],
        [0.5686275 , 0.5647059 , 0.6901961 ]],

       ...,

       [[0.53333336, 0.53333336, 0.6745098 ],
        [0.5294118 , 0.5294118 , 0.67058825],
        [0.5294118 , 0

In [12]:
x_val[5][50:100, 60:100]

array([[[0.8117647 , 0.5764706 , 0.5764706 ],
        [0.8156863 , 0.5803922 , 0.5803922 ],
        [0.8156863 , 0.5803922 , 0.5803922 ],
        ...,
        [0.8352941 , 0.6156863 , 0.6117647 ],
        [0.83137256, 0.6117647 , 0.60784316],
        [0.83137256, 0.6117647 , 0.60784316]],

       [[0.8117647 , 0.5764706 , 0.5764706 ],
        [0.8117647 , 0.5803922 , 0.5803922 ],
        [0.8117647 , 0.5803922 , 0.5803922 ],
        ...,
        [0.83137256, 0.6156863 , 0.60784316],
        [0.83137256, 0.6156863 , 0.60784316],
        [0.83137256, 0.6117647 , 0.6039216 ]],

       [[0.8117647 , 0.5764706 , 0.5764706 ],
        [0.8117647 , 0.58431375, 0.5803922 ],
        [0.8117647 , 0.58431375, 0.5803922 ],
        ...,
        [0.8352941 , 0.61960787, 0.60784316],
        [0.8352941 , 0.61960787, 0.60784316],
        [0.83137256, 0.6156863 , 0.6039216 ]],

       ...,

       [[0.8509804 , 0.6431373 , 0.61960787],
        [0.8509804 , 0.6431373 , 0.6117647 ],
        [0.8509804 , 0

In [13]:
x_test[5][50:100, 60:100]

array([[[0.7490196 , 0.5686275 , 0.5686275 ],
        [0.7490196 , 0.5686275 , 0.5686275 ],
        [0.74509805, 0.5647059 , 0.5647059 ],
        ...,
        [0.75686276, 0.58431375, 0.5803922 ],
        [0.75686276, 0.58431375, 0.5803922 ],
        [0.75686276, 0.58431375, 0.5803922 ]],

       [[0.74509805, 0.5686275 , 0.5686275 ],
        [0.7490196 , 0.5686275 , 0.5686275 ],
        [0.74509805, 0.5647059 , 0.5647059 ],
        ...,
        [0.7607843 , 0.5882353 , 0.5764706 ],
        [0.7607843 , 0.5882353 , 0.5764706 ],
        [0.7607843 , 0.5882353 , 0.5803922 ]],

       [[0.74509805, 0.5647059 , 0.5647059 ],
        [0.7490196 , 0.5647059 , 0.5647059 ],
        [0.74509805, 0.5647059 , 0.5647059 ],
        ...,
        [0.7607843 , 0.5882353 , 0.5764706 ],
        [0.7607843 , 0.5882353 , 0.5764706 ],
        [0.7647059 , 0.5921569 , 0.5803922 ]],

       ...,

       [[0.77254903, 0.6117647 , 0.5882353 ],
        [0.77254903, 0.6117647 , 0.5882353 ],
        [0.7764706 , 0

In [14]:
np.save("x_train_norm_200.npy", x_train)
np.save("y_train_norm_200.npy", y_train)

np.save("x_val_norm_200.npy", x_val)
np.save("y_val_norm_200.npy", y_val)

np.save("x_test_norm_200.npy", x_test)
np.save("y_test_norm_200.npy", y_test)